support updating k8s cluster grid cli
threefoldtech/tfgrid-sdk-go pull request #1145
Opened 2024-08-04 11:05 UTC by Eslam-Nawara

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2024-08-05 09:33 UTC, rawdaGastan commented
Can you update the docs with `update cmd`?

2024-08-05 10:06 UTC, rawdaGastan requested changes
🔥 🔥

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/update_kubernetes.go
> +// deployCmd represents the deploy command
update the comment :D

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +		workerNumber, err := cmd.Flags().GetInt("workers-number")
`workerNumber` -> `workersNumber`?

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +			log.Fatal().Err(err).Send()
Why using `fatal` here instead of return?
also next ones

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +		if len(workers) > 0 {
I can't understand this part, why setting worker to the first one in the cluster?

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +			filter, disks, rootfss := filters.BuildK8sFilter(worker, workersFarm)
I think here will give you resources for one worker only?

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +		cluster, err = command.GetK8sCluster(cmd.Context(), t, name)
I think no need to get cluster as `AddWorkersKubernetesCluster` already returns the loaded one?

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/delete_worker_kubernetes.go
> +	Short: "remove workder from a kubernetes cluster",
`worker` :D

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/delete_worker_kubernetes.go
> +			log.Fatal().Err(err).Send()
Why `fatal` here too?

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/cmd/delete_worker_kubernetes.go
> +		}
I think just a msg it is deleted it enough? no?

2024-08-05 10:06 UTC, rawdaGastan commented on grid-cli/internal/cmd/update.go
> +	time.Sleep(10 * time.Second)
add a comment why we `sleep` here

2024-08-05 10:18 UTC, rawdaGastan requested changes

2024-08-05 10:18 UTC, rawdaGastan commented on grid-cli/docs/kubernetes.md
> +tfcmd apdate kubernetes add [flags]
`update`

2024-08-05 10:18 UTC, rawdaGastan commented on grid-cli/docs/kubernetes.md
> +- workers-farm: farm id workers should be deployed on, if set choose available node from farm that fits master specs (default 1). note: workers-node and workers-farm flags cannot be set both.
`workers-nodes`

2024-08-05 10:18 UTC, rawdaGastan commented on grid-cli/docs/kubernetes.md
> +> **Note:** optional flags other than workers-number and workers-nodes will be applied only if the cluster has no worker, other wise they will be ignored and the options used on cluster creation will
why?

2024-08-05 10:18 UTC, rawdaGastan commented on grid-cli/docs/kubernetes.md
> +➜  grid-cli git:(development-support-updating-k8s-cluster-grid-cli) ✗ go run main.go deploy kubernetes --name test --ssh ~/.ssh/id_rsa.pub --workers-number 1 --master-memory 2 --mycelium
remove `grid-cli git:(development-support-updating-k8s-cluster-grid-cli) ✗ go run main.go` and add `tfcmd .. `

check others

2024-08-05 10:18 UTC, rawdaGastan commented on grid-cli/docs/kubernetes.md
> +tfcmd apdate kubernetes delete [flags]
`update`

2024-08-05 10:25 UTC, Eslam-Nawara commented on grid-cli/cmd/add_worker_kubernetes.go
> +			log.Fatal().Err(err).Send()
because it's not a usage error, returning an error here will cause a usage error

2024-08-05 13:12 UTC, Eslam-Nawara commented on grid-cli/cmd/add_worker_kubernetes.go
> +			filter, disks, rootfss := filters.BuildK8sFilter(worker, workersFarm)
yes, every worker will be in separate node

2024-08-05 13:16 UTC, Eslam-Nawara commented on grid-cli/cmd/add_worker_kubernetes.go
> +		cluster, err = command.GetK8sCluster(cmd.Context(), t, name)
we need to get the deployed workers in the cluster to add the new workers to

2024-08-05 13:17 UTC, Eslam-Nawara commented on grid-cli/cmd/delete_worker_kubernetes.go
> +			log.Fatal().Err(err).Send()
https://github.com/threefoldtech/tfgrid-sdk-go/pull/1145#discussion_r1703900148

2024-08-05 13:18 UTC, Eslam-Nawara commented on grid-cli/cmd/delete_worker_kubernetes.go
> +		}
and remove the load part?

2024-08-06 12:45 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +			filter, disks, rootfss := filters.BuildK8sFilter(worker, workersFarm)
but you are requesting more than 1 node

2024-08-06 12:46 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +		cluster, err = command.GetK8sCluster(cmd.Context(), t, name)
it is returned from `AddWorkersKubernetesCluster` but it is ignored

2024-08-06 12:47 UTC, rawdaGastan commented on grid-cli/cmd/delete_worker_kubernetes.go
> +		}
I think yes no need to get after delete

2024-08-06 12:47 UTC, rawdaGastan commented on grid-cli/cmd/add_worker_kubernetes.go
> +		cluster, err = command.GetK8sCluster(cmd.Context(), t, name)
here: https://github.com/threefoldtech/tfgrid-sdk-go/pull/1145/files#diff-e8a15c2927cce4ca74d905d0ef9551712856a3c90a7f3c19799a7f14f9e959a8R53

2024-08-08 07:54 UTC, Eslam-Nawara commented on grid-cli/cmd/add_worker_kubernetes.go
> +		cluster, err = command.GetK8sCluster(cmd.Context(), t, name)
ahaaaaa I got it :D

2024-08-08 10:17 UTC, rawdaGastan approved these changes

2024-08-08 13:29 UTC, merged