support network and machine light
threefoldtech/tfgrid-sdk-go pull request #1223
Opened 2024-10-10 14:05 UTC by rawdaGastan

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-go/issues/1213

### Try

- https://github.com/threefoldtech/tfgrid-sdk-go/blob/c59cf061a57a7b793c8e2d9034a30b5c8401fcb5/grid-client/scripts/deploy_single_vm_with_mycelium_light/main.go

2024-10-15 11:57 UTC, ashraffouda requested changes

2024-10-15 11:57 UTC, ashraffouda commented on grid-client/integration_tests/setup.go
> +	mnemonics := "winner giant reward damage expose pulse recipe manual brand volcano dry avoid"
remove ur mnemonics

2024-10-15 11:57 UTC, ashraffouda commented on grid-client/integration_tests/setup.go
> +	network := "dev"
get the Network back from the env

2024-10-16 10:15 UTC, xmonader requested changes

2024-10-16 10:15 UTC, xmonader commented on grid-client/zos/deployment.go
> +func (d *Deployment) zosDeployment4() *gridtypes4.Deployment {
Should we make it `ZosDeployment4` to be consistent with `ZosDeployment`

2024-10-16 10:15 UTC, xmonader commented on grid-client/workloads/vm_light.go
> +func (vm *VMLight) LoadFromVM(vm2 *VM) {
should we support also a `LoadFromVMLight`?

2024-10-17 06:56 UTC, Eslam-Nawara commented on grid-client/deployer/network_deployer.go
> +			d.tfPluginClient.TwinID, publicNode, allNodes, endpoints, nodeUsedPorts,
why not passing the plugin instead

2024-10-17 07:55 UTC, Eslam-Nawara commented on grid-client/deployer/network_deployer.go
> +		if endpoints[nodeID] != nil && endpoints[nodeID].To4() != nil {
if the network already has a public node here, we don't need to loop over all nodes to check if there's a public node right?

2024-10-17 09:55 UTC, Eslam-Nawara commented on grid-client/state/state.go
> +	znet.NodesIPRange = nodesIPRange
should we get mycelium keys too?

2024-10-17 11:34 UTC, Eslam-Nawara commented on grid-client/zos/ipnet.go
> +	//fmt.Println("parsing: ", string(text))
remove this please

2024-10-17 11:47 UTC, Eslam-Nawara commented on grid-client/zos/ipnet.go
> +// MarshalJSON dumps iprange as a string
`MarshalText`

2024-10-17 12:56 UTC, Eslam-Nawara commented on grid-client/zos/machine_light.go
> +	// to yggdrasil support. Otherwise (if mycelium is set) a mycelium ip is used instead.
no ygg here no?

2024-10-17 13:12 UTC, Eslam-Nawara commented on grid-client/zos/workload.go
> +}
```suggestion
	return slices.Contains(state, s)
}
```

2024-10-20 09:18 UTC, Eslam-Nawara commented on grid-client/workloads/network_interface.go
> +	generateDeployments(endpointIPs map[uint32]net.IP, usedPorts map[uint32][]uint16, publicNode, twinID uint32,
why is this added to the interface? isn't it just a helper function?

2024-10-21 10:02 UTC, rawdaGastan commented on grid-client/zos/machine_light.go
> +	// to yggdrasil support. Otherwise (if mycelium is set) a mycelium ip is used instead.
no ygg or public ips

2024-10-21 10:27 UTC, xmonader approved these changes

2024-10-21 10:30 UTC, ashraffouda approved these changes

2024-10-21 10:33 UTC, Eslam-Nawara commented on grid-client/state/state.go
> +	}
momken n add this to the previous loop? you already loop over the zNets there

2024-10-21 10:34 UTC, Eslam-Nawara commented on grid-client/state/state.go
> +	myceliumKeys := make(map[uint32][]byte)
same here

2024-10-21 10:43 UTC, Eslam-Nawara approved these changes

2024-10-21 10:52 UTC, merged