disable output styling for cli and tfrobot
threefoldtech/tfgrid-sdk-go pull request #1242
Opened 2024-11-04 11:36 UTC by Eslam-Nawara

### Description

add flag to disable output styling for cli and tfrobot

### Related Issues

- #1211 
- 
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2024-12-22 11:07 UTC, rawdaGastan commented
Can you update the pr with the difference?

2025-01-20 08:54 UTC, Eslam-Nawara commented
here I loaded a deployment with and without --no-color flag 
```sh
➜  grid-cli git:(development-disable-output-styling-cli) ✗ go run main.go get vm test &> output1
➜  grid-cli git:(development-disable-output-styling-cli) ✗ go run main.go get vm test --no-color &> output2

```

and as the issue specifies the output is wrapped in escape sequences, so I added an option to disable that if the user need to get the values without wrapping them
![image](https://github.com/user-attachments/assets/b15006d2-0e69-4feb-8603-b918c9d07c3f)

2025-01-27 12:33 UTC, rawdaGastan requested changes

2025-01-27 12:33 UTC, rawdaGastan commented on grid-cli/cmd/get_contract.go
> +			return
How would I know the error here? check other files

2025-01-27 12:33 UTC, rawdaGastan commented on grid-cli/cmd/get_contract.go
> +	getContractCmd.Flags().Bool("no-color", false, "disable output styling")
why not adding it to the parent command instead of adding it for every subcommand?

2025-01-27 12:33 UTC, rawdaGastan commented on tfrobot/cmd/cancel.go
> -		zerolog.SetGlobalLevel(zerolog.InfoLevel)
why removing this?

2025-01-27 12:33 UTC, rawdaGastan commented on tfrobot/cmd/deploy.go
> +		if errs := deployer.RunDeployer(context.Background(), cfg, tfPluginClient, outputPath, debug); errs != nil {
why not taking command ctx?

2025-01-27 12:33 UTC, rawdaGastan commented on tfrobot/cmd/load.go
> +		if err := deployer.RunLoader(context.Background(), cfg, tfPluginClient, debug, outputPath); err != nil {
same here, why not using command ctx?

2025-03-06 10:20 UTC, Eslam-Nawara commented on tfrobot/cmd/cancel.go
> -		zerolog.SetGlobalLevel(zerolog.InfoLevel)
setting up tfpluging client now handles this part https://github.com/threefoldtech/tfgrid-sdk-go/pull/1242/files#diff-b730e7c9c0bc98a6d06902de8848653e959db99941da2fa028ca33184e1dbb23R38

2025-03-06 11:01 UTC, rawdaGastan approved these changes

2025-03-06 11:08 UTC, merged