init bridge monitoring tests
threefoldtech/tfgrid-sdk-go pull request #384
Opened 2023-09-17 15:18 UTC by Omarabdul3ziz

### Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/383

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstring

2023-09-18 11:26 UTC, xmonader commented on monitoring-bot/internal/constants.go
> +	tftIssuerAddress    = "GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3"
the address is different on networks

2023-09-18 13:08 UTC, rawdaGastan requested changes

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/README.md
> +- the balance in accounts and send warnings if it is under some threshold.
add bridge report

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/README.md
> +    BRIDGE_MON_INTERVAL_MIN=<number of minutes between each bridge test report>
I think we can use mins?

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +			fmt.Println(err.Error())
can we use zerolog instead?

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +func (m *Monitor) monitorBridge(net network) (string, error) {
I think we should return the error and check which msg to report in `monitorBridges`

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +func (m *Monitor) sendToTfChain(tfChain network) error {
`tfChain` should be net?

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +		return fmt.Errorf("failed to get twinId: %w", err)
`twinId` should be `twin id` (because it's an uppercase char)

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +func (m *Monitor) sendToStellar(tfChain network) error {
tfChain ->  net?

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +	strClient := horizonclient.DefaultTestNetClient
is it for test and public?

2023-09-18 13:08 UTC, rawdaGastan commented on monitoring-bot/internal/monitor.go
> +	if err != nil || res.StatusCode >= 400 {
there is no error for the second case

2023-09-25 10:44 UTC, rawdaGastan requested changes

2023-09-25 10:44 UTC, rawdaGastan commented on monitoring-bot/internal/monitor.go
> +		return fmt.Errorf("failed to send http post request: %w", err)
can we make error msgs -> `failed to send telegram message request` 
- for res.StatusCode >= 400 also

2023-09-25 10:44 UTC, rawdaGastan commented on monitoring-bot/internal/monitor.go
>  func (m *Monitor) sendMessage(manager client.Manager, wallet wallet) error {
can we rename func 
for example `balanceAlert`

2023-09-25 10:44 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +		return balanceReport{}, fmt.Errorf("failed to get balance for account ")
you didn't wrap the error

2023-09-25 10:44 UTC, rawdaGastan commented on monitoring-bot/internal/bridge.go
> +			return 0, fmt.Errorf("failed to get balance for account ")
you didn't wrap the error

2023-09-25 10:46 UTC, rawdaGastan commented
can you please update the report msg in the description?

2023-09-26 09:08 UTC, rawdaGastan approved these changes

2023-09-26 09:09 UTC, merged