update monitoring-bot README.md
threefoldtech/tfgrid-sdk-go pull request #442
Opened 2023-10-29 11:24 UTC by Eslam-Nawara

### Description

update monitoring bot readme file 

### Changes

change the binary name from monitoring-bot to tfgridmon

### Related Issues

- #431

2023-10-29 11:35 UTC, rawdaGastan requested changes

2023-10-29 11:35 UTC, rawdaGastan commented on monitoring-bot/README.md
> +    sudo cp tfgridmon /usr/local/bin
we should rename the one in the makefile to `monitoring-bot` for `build` command
goreleaser has the name `monitoring-bot` for the bin

2023-10-29 11:38 UTC, AbdelrahmanElawady commented on monitoring-bot/README.md
> +    sudo cp tfgridmon /usr/local/bin
this part of the documentation is using the release artifact which first need to use tar and the binary is called `monitoring-bot`

2023-10-29 12:58 UTC, AbdelrahmanElawady approved these changes

2023-11-01 08:56 UTC, rawdaGastan approved these changes

2023-11-01 08:57 UTC, merged