Add encoding options to peer
threefoldtech/tfgrid-sdk-go pull request #526
Opened 2023-12-04 11:34 UTC by AbdelrahmanElawady

### Description

Add encoding options to RMB Peer and defaults for Peer arguments.

### Related Issues

- #507 

### Checklist

- [ ] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstring

2023-12-06 08:42 UTC, muhamadazmy requested changes

2023-12-06 08:42 UTC, muhamadazmy commented on rmb-sdk-go/peer/encoder/json.go
> +func newJSONEncoder() Encoder {
This should be public IMHO, even if it's the default the user should still explictely pass it as an option

2023-12-06 08:42 UTC, muhamadazmy commented on rmb-sdk-go/peer/peer.go
> +		enableEncryption: false,
encryption should be `true` by default actually. only disable explicetly via the option

2023-12-06 08:42 UTC, muhamadazmy commented on rmb-sdk-go/peer/peer.go
> +	}
This is not the right way. This basically means that NewEncoder need to be modified everytime you have to implement a new encoding type. 

What if in another app i wanna use this with "binary" encoding, do i have to fork and modify your library before i can do this ?

The correct way to do this instead is that your option instead must be  `WithEncoder` (or something) that takes an instance of Encoder type. 

If encoder is not set (yourc `cfg.encoder` is still nil after applying all the Withs) then you can then create the default JsonEncoder and use that.

2023-12-06 08:42 UTC, muhamadazmy commented on rmb-sdk-go/peer/peer.go
> +func WithEncoder(schema encoder.Schema) PeerOpt {
Check the other comment, this instead should take `Encoder` not Schema! to make it easier for developer to implement their own encoder types. without the need to modify this library code

2023-12-06 08:42 UTC, muhamadazmy commented on rmb-sdk-go/peer/peer.go
> +		encoder: e,
I think the Peer need to also may have function `Encoder() Encoder` that returns the encoder. This allows handler to then use the encode to `decode` payloads. if they match expected schema.

```go
func (p *Peer) Encoder() Encoder {
   return p.encoder
}
```

2023-12-06 08:42 UTC, muhamadazmy commented on rmb-sdk-go/peer/encoder/encoder.go
> +func NewEncoder(schema Schema) (Encoder, error) {
Check the other comment regarding how the encoder need to be configured. 

In short, This means that user of this library cannot use custom encoding unless this library is modified (or forked) Instead the `WithEncoder` need to take an encoder object, not schema. Hence I (as a 3rd party) can implement my cutsom encoder type.

2023-12-13 08:23 UTC, xmonader approved these changes

2023-12-19 12:17 UTC, muhamadazmy approved these changes

2023-12-19 12:22 UTC, merged